#! /bin/sh
# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# set a random wallpaper
#setbg `find "$HOME/Pictures/wallpapers/" | sort -R | tail -n 1` &
setbg
# keybinds
pgrep sxhkd || sxhkd &
# start dunst for notifcation
pgrep dunst || dunst &
# bar
"$HOME/dotfiles/polybar/launch.sh" &
# remaps
remaps &
# compositor
picom -bc --config "$HOME/.config/picom.conf"
# hide cursor
unclutter &
# autolocking
pgrep autolock || autolock &

bspc desktop -f 1

bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# application rules
bspc rule -a discord desktop='^10'
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Soffice desktop='^5'
bspc rule -a Tde:\* border=off
bspc rule -a firefox:Toolkit state=floating sticky=on
bspc rule -a Spotify desktop='^9'
bspc rule -a Peek state=floating

# fix intellij and possibly other stupid applications
wmname LG3D

# computer specific settting
case $HOSTNAME in
    thinky)
        # workspaces on the internal display
        bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10

        # sort of good gaps
        bspc config border_width       2
        bspc config window_gap         4
        bspc config bottom_padding    -6
        bspc config left_padding      -6
        bspc config right_padding     -6

        # trackpad fixes
        tpID=`xinput list | grep TouchPad | grep -o '[0-9][0-9]'`
        scrollID=`xinput list-props $tpID | grep "Scrolling Distance" | grep -o '[0-9][0-9][0-9]' | head -1`
        accelID=`xinput list-props $tpID | grep "Accel Profile" | grep -o '[0-9][0-9][0-9]'`
        xinput set-prop $tpID $scrollID -133 -133
        xinput set-prop $tpID $accelID 0

        # blue light filter
        pgrep redshift || redshift-gtk &
        ;;
    archy)
        # workspace setup
        bspc wm --reorder-monitors DVI-D-0 DP-3 HDMI-0
        bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8
        bspc monitor DP-3 -d 9
        bspc monitor HDMI-0 -d 10
        # make sure the refresh rate is right
        xrandr --output DVI-D-0 --mode 1920x1080 --rate 144

        # gaps that aren't hideous on multi monitor setups
        bspc config border_width       2
        bspc config window_gap          0
        ;;
    trashy)
        # monitor
        bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10
        xrandr --output DVI-I-1 --mode 1920x1080 --rate 144
esac
