#! /bin/sh
if [[ $(hostname) == 'archy' ]]; then
    bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
    bspc monitor HDMI-0 -d 10
elif [[ $(hostname) == 'thinky' ]]; then
    bspc monitor eDP -d 1 2 3 4 5 6 7 8 9 10
elif [[ $(hostname) == 'haunter' ]]; then
    bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 10
elif [[ $(hostname) == 'trashy' ]]; then
    bspc monitor DVI-I-1 -d 1 2 3 4 5 6 7 8 9
    #bspc monitor DP-1 -d 1 2 3 4 5 6 7 8 9 10
    bspc monitor DP-1 -d 10
fi

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"
# set a random wallpaper
setbg `find "$HOME/Pictures/wallpapers/" | sort -R | tail -n 1` &
# keybinds
sxhkd &
# start dunst for notifcation
dunst &
# bar
"$HOME/dotfiles/polybar/launch.sh" &
# remaps
remaps &
# compositor
picom -bc --config "$HOME/.config/picom.conf"
# hide cursor
unclutter &
# autolocking
autolock &
# redshift
redshift-gtk &

bspc desktop -f 1

bspc config border_width         2
bspc config window_gap          10
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# application rules
bspc rule -a discord desktop='^10'
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a Soffice desktop='^5'
bspc rule -a Tde:\* border=off
bspc rule -a firefoxdeveloperedition:Toolkit state=floating sticky=on


case $HOSTNAME in
    thinky)
        tpID=`xinput list | grep TouchPad | grep -o '[0-9][0-9]'`
        scrollID=`xinput list-props $tpID | grep "Scrolling Distance" | grep -o '[0-9][0-9][0-9]' | head -1`
        accelID=`xinput list-props $tpID | grep "Accel Profile" | grep -o '[0-9][0-9][0-9]'`
        xinput set-prop $tpID $scrollID -133 -133
        xinput set-prop $tpID $accelID 0
        ;;
    archy)
        xrandr --output DVI-D-0 --mode 1920x1080 --rate 144
        ;;
    trashy)
        xrandr --output DVI-I-1 --mode 1920x1080 --rate 144
esac
