#! /bin/sh
if [[ $(hostname) == 'archy' ]]; then
    bspc monitor DVI-D-0 -d 1 2 3 4 5 6 7 8 9
    bspc monitor HDMI-0 -d 10
elif [[ $(hostname) == 'thinky' ]]; then
    bspc monitor VGA-0 -d I II III IV V
    bspc monitor VGA-1 -d VI VII VIII IX X
elif [[ $(hostname) == 'haunter' ]]; then
    bspc monitor LVDS1 -d 1 2 3 4 5 6 7 8 9 10
fi

# If refreshing bspwm, remove all previous rules to prevent doubling up.
bspc rule -r "*"

# keybinds
sxhkd &
# start dunst for notifcation
dunst &
# bar
"$HOME/dotfiles/polybar/launch.sh" &
# remaps
remaps &
# compositor
picom -bc --config "$HOME/.config/picom.conf"
# hide cursor
unclutter &
# autolocking
autolock &

bspc desktop -f 1

bspc config border_width         2
bspc config window_gap          12
bspc top_padding 24
bspc config focus_follows_pointer true

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# application rules
bspc rule -a discord desktop='^10'
bspc rule -a Screenkey manage=off
bspc rule -a libreoffice desktop='^5'

